# Data cleaning and preparation
We have splitted our data into train and test, but did not make any other modifications. To make our data fit for machine learning, we need to:
* Handle missing, corrupt or incorrect data
* Do feature normalization

Let's start by looking how much missing data we have:

In [3]:
import pandas as pd
weather_train = pd.read_csv('data/weather_train.csv')

In [4]:
weather_train.isna().sum().sum()

0

We have no missing values so we can continue.

It could also be that we have corrupt data, leading e.g. to outliers in the data set. The pair plot in the previous episode could have hinted to this. For this dataset, we don't need to do anything about outliers.

## Feature normalization
As we saw in the pairplot, the magnitudes of the different features are not directly comparable with each other. Some of the features are in mm, others in degrees celcius, and the scales are different.

Most Machine Learning algorithms regard all features together in one multi-dimensional space. To do calculations in this space that make sense, the features should be comparable to each other, e.g. they should be scaled. There are two options for scaling:
- Normalization (Min-Max scaling)
- Standardization (scale by mean and variance)
In this case, we choose min_max scaling, because we do not know much about the distribution of our features. If we know that (some) features have a normal distrubtion, it makes more sense to do standardization.

In [1]:
import sklearn.preprocessing
min_max_scaler = sklearn.preprocessing.MinMaxScaler()

In [5]:
feature_names = weather_train.columns[1:]

In [6]:
weather_train_scaled = weather_train.copy()
weather_train_scaled[feature_names] = min_max_scaler.fit_transform(weather_train[feature_names])

### Exercise
Compare the distributions of the numerical features before and after scaling. What do you notice?

In [13]:
weather_train.describe()

,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,...,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max
count,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,...,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000
mean,6.438642,5.485640,0.754778,1.017806,1.290052,0.263773,4.572193,11.236292,7.292820,15.624543,...,5.272063,11.545039,3.871671,0.799987,1.016433,1.286057,0.225927,12.137859,7.947128,16.329504
std,3.461575,2.346835,0.102952,0.008106,0.942928,0.522791,4.340088,6.850607,6.102385,8.113162,...,7.435019,8.944256,1.581145,0.102116,0.008825,0.910704,0.458577,5.815459,5.230505,6.934869
min,1.000000,0.000000,0.460000,0.988200,0.060000,0.000000,0.000000,-7.600000,-13.000000,-5.500000,...,-19.700000,-13.000000,0.800000,0.480000,0.976200,0.050000,0.000000,-3.500000,-6.900000,-1.400000
25%,3.000000,4.000000,0.680000,1.013200,0.490000,0.000000,0.400000,6.500000,3.225000,9.400000,...,-0.075000,4.225000,2.800000,0.730000,1.011400,0.490000,0.000000,8.000000,4.300000,11.300000
50%,6.000000,6.000000,0.760000,1.017300,1.030000,0.000000,3.500000,11.250000,7.450000,15.400000,...,5.500000,11.000000,3.600000,0.810000,1.016700,1.125000,0.020000,11.850000,8.300000,15.900000
75%,9.000000,7.000000,0.840000,1.022500,1.990000,0.300000,7.800000,16.900000,12.000000,22.375000,...,11.500000,18.800000,4.900000,0.880000,1.021800,1.947500,0.220000,16.875000,11.875000,21.400000
max,12.000000,8.000000,0.980000,1.040600,3.520000,4.110000,15.300000,26.800000,18.700000,34.500000,...,20.400000,31.800000,9.600000,0.980000,1.038300,3.560000,3.800000,26.200000,21.200000,34.400000

In [12]:
weather_train_scaled.describe()

,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,...,STOCKHOLM_temp_min,STOCKHOLM_temp_max,TOURS_wind_speed,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max
count,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,...,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000,766.000000
mean,6.438642,0.685705,0.566881,0.565003,0.355506,0.064178,0.298836,0.547567,0.640152,0.528114,...,0.622745,0.547880,0.349054,0.639974,0.647869,0.352153,0.059454,0.526527,0.528368,0.495238
std,3.461575,0.293354,0.197984,0.154692,0.272523,0.127200,0.283666,0.199146,0.192504,0.202829,...,0.185412,0.199649,0.179676,0.204231,0.142106,0.259460,0.120678,0.195807,0.186139,0.193711
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,0.500000,0.423077,0.477099,0.124277,0.000000,0.026144,0.409884,0.511830,0.372500,...,0.489401,0.384487,0.227273,0.500000,0.566828,0.125356,0.000000,0.387205,0.398577,0.354749
50%,6.000000,0.750000,0.576923,0.555344,0.280347,0.000000,0.228758,0.547965,0.645110,0.522500,...,0.628429,0.535714,0.318182,0.660000,0.652174,0.306268,0.005263,0.516835,0.540925,0.483240
75%,9.000000,0.875000,0.730769,0.654580,0.557803,0.072993,0.509804,0.712209,0.788644,0.696875,...,0.778055,0.709821,0.465909,0.800000,0.734300,0.540598,0.057895,0.686027,0.668149,0.636872
max,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

We save the data to use in our next notebook

In [7]:
weather_train_scaled.to_csv('data/weather_train_scaled.csv', index=False)